### ISSUE TITLE
[Naming] Call your Serializers what they are

### ISSUE THREAD

**Issue by jzornow** [SonderMindOrg/sober_swag#12]
I think you named these `Blueprint` because that's the serialization library we're using in our apps, but these are serializers. Let's call them that for the sake of intuition.

**Comment by AnthonySuper** [comment]
Do you mind if I call them `ObjectSerializer`s? As that's more descriptive (and you can already have serializers for non-objects that are *not* blueprints)

**Comment by jzornow** [comment]
👍 Sounds good to me.
