### ISSUE TITLE
Coerce Types::JSON::Hash into a valid Swagger object

### ISSUE THREAD

**Issue by connorshea** [SonderMindOrg/sober_swag#59]
`Types::JSON::Hash` doesn't get serialized correct into something that Swagger understands.

This causes problems because you get errors in the Swagger output and tooling doesn't understand what to do with it.

It should probably coerce it into an object somehow? Also, we should probably error if the user attempts to use a type that we don't understand? Is that possible?

**Comment by AnthonySuper** [comment]
This got fixed in v0.18.
