### ISSUE TITLE
Don't use oneOf when there's only one object

### ISSUE THREAD

**Issue by connorshea** [SonderMindOrg/sober_swag#60]
SoberSwag will output something like this for the response type even though there's only one option:

```json
{
  "schema": {
    "oneOf": [
      {
        "$ref": "#/components/schemas/PersonResponse"
      }
    ]
  }
}
```

It shouldn't use `oneOf` in this case.

This is especially noticeable when you open the `Schema` (the option next to 'Example response') in the Swagger UI.

I believe the fix would be to output this instead:

```json
{
  "schema": {
    "$ref": "#/components/schemas/PersonResponse"
  }
}
```

**Comment by connorshea** [comment]
Example:

<img width="1288" alt="Screen Shot 2020-11-30 at 3 37 27 PM" src="https://user-images.githubusercontent.com/2977353/100674178-fb6b9080-3321-11eb-95bf-849938963da2.png">

**Comment by AnthonySuper** [comment]
The reason we do this is to allow adding `description` on keyed schemas. This is invalid swagger:

```json
{
  "schema": {
    "$ref": "#/schemas/MyCoolOjbect",
    "description": "It's a cool object"
  }
}
```

You need the additional layer of nesting as a hacky workaround for that problem. I think a proper fix would be to *only* generate the `oneOf` wrapper if there is a description, but that might be kinda gross to code.

**Comment by AnthonySuper** [comment]
Fixed in SoberSwag reporting.
