### ISSUE TITLE
Incorrect JSON created by SoberSwag for a request parameter with a description

### ISSUE THREAD

**Issue by connorshea** [SonderMindOrg/sober_swag#62]
If I have something like this in my Rails controller:

```ruby
define :get, :show, '/pets/{id}' do
  summary 'Get the pet'

  path_params do
    attribute :id, SoberSwag::Types::Params::Integer.meta(
      description: 'The ID of the pet.'
    )
  end
end
def show; end
```

SoberSwag generates this:

```json
"parameters": [
  {
    "name": "id",
    "schema": {
      "type": "integer",
      "description": "The ID of the pet."
    },
    "required": true,
    "in": "path"
  }
]
```

But in [petstore demo](https://petstore.swagger.io/), this is what's generated (and presumably, what Swagger UI expects):

```json
"parameters": [
  {
    "name": "id",
    "type": "integer",
    "description": "The ID of the pet.",
    "required": true,
    "in": "path"
  }
]
```

So the description of the parameter doesn't get displayed in Swagger UI when you use SoberSwag, because it's under the `schema` key. We should fix this so it generates the expected structure.

**Comment by AnthonySuper** [comment]
The [documentation for path parameters](https://swagger.io/docs/specification/describing-parameters/) uses a `schema` key. The petstore demo you linked is using swagger version `2.0.0`, when SoberSwag generates documentation for `3.0.0`. So I think this is just a version difference.
